<?php

namespace Database\Seeders;

use App\Models\AcademicLevel;
use Illuminate\Database\Seeder;
use Str;

class AcademicLevelSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => Str::uuid(),
                'level' => 'تحضيري',
                'phase' => 'الطور الابتدائي',
                'phase_key' => 'primary_education',
                'subject_ids' => json_encode([11, 27, 3, 5, 6, 4, 7, 9]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى ابتدائي',
                'phase' => 'الطور الابتدائي',
                'phase_key' => 'primary_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 3, 5, 26, 6, 4, 8, 9, 7]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ابتدائي',
                'phase' => 'الطور الابتدائي',
                'phase_key' => 'primary_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 3, 5, 26, 6, 4, 8, 7]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ابتدائي',
                'phase' => 'الطور الابتدائي',
                'phase_key' => 'primary_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 3, 5, 26, 6, 4, 8, 7]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الرابعة ابتدائي',
                'phase' => 'الطور الابتدائي',
                'phase_key' => 'primary_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 3, 5, 26, 6, 4, 8, 7]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الخامسة ابتدائي',
                'phase' => 'الطور الابتدائي',
                'phase_key' => 'primary_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 3, 5, 26, 6, 7, 4, 8]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى المتوسط',
                'phase' => 'الطور المتوسط',
                'phase_key' => 'middle_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 1, 15, 3, 5, 26, 28, 4, 8, 29]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية المتوسط',
                'phase' => 'الطور المتوسط',
                'phase_key' => 'middle_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 1, 15, 3, 5, 26, 28, 4, 8, 29]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة المتوسط',
                'phase' => 'الطور المتوسط',
                'phase_key' => 'middle_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 1, 15, 3, 5, 26, 28, 4, 8, 29]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الرابعة المتوسط',
                'phase' => 'الطور المتوسط',
                'phase_key' => 'middle_education',
                'subject_ids' => json_encode([11, 27, 13, 12, 2, 1, 15, 3, 5, 26, 28, 4, 8, 29]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى ثانوي آداب',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 1, 15, 31, 2, 13, 12, 28, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى ثانوي علوم',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 1, 15, 31, 2, 13, 12, 28, 32, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي رياضيات',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 15, 1, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي تقني رياضي (هندسة مدنية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 20, 1, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي تقني رياضي (هندسة الطرائق)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 23, 1, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي تقني رياضي (هندسة ميكانيكية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 22, 1, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي تقني رياضي (هندسة كهربائية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 21, 1, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي علوم تجريبية',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 15, 1, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي تسيير و اقتصاد',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 18, 19, 17, 31, 2, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي أدب و فلسفة',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 16, 2, 31, 13, 12, 1, 15, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي لغات أجنبية (اللغة الألمانية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 12, 13, 24, 31, 2, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي لغات أجنبية (اللغة الإسبانية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 12, 13, 25, 31, 2, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ثانوي لغات أجنبية (اللغة الإيطالية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 12, 13, 14, 31, 2, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي رياضيات',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 15, 1, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي تقني رياضي (هندسة مدنية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 20, 1, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي تقني رياضي (هندسة الطرائق)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 23, 1, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي تقني رياضي (هندسة ميكانيكية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 22, 1, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي تقني رياضي (هندسة كهربائية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 21, 1, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي علوم تجريبية',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 15, 1, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي تسيير و إقتصاد',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 18, 19, 17, 31, 2, 13, 12, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي أدب و فلسفة',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 16, 2, 31, 13, 12, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي لغات أجنبية (اللغة الألمانية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 12, 13, 24, 31, 2, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي لغات أجنبية (اللغة الإسبانية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 12, 13, 24, 31, 2, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ثانوي لغات أجنبية (اللغة الإيطالية)',
                'phase' => 'الطور الثانوي',
                'phase_key' => 'secondary_education',
                'subject_ids' => json_encode([30, 11, 12, 13, 24, 31, 2, 16, 29, 26]),
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى ليسانس',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,

            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ليسانس',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة ليسانس',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى ماستر',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية ماستر',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الأولى دكتوراه',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثانية دكتوراه',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الثالثة دكتوراه',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الرابعة دكتوراه',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'الخامسة دكتوراه',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'متخرج',
                'phase' => 'الطور الجامعي',
                'phase_key' => 'university',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الأولى',
                'phase' => 'الشبه طبي',
                'phase_key' => 'paramedical',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الثانية',
                'phase' => 'الشبه طبي',
                'phase_key' => 'paramedical',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الثالثة',
                'phase' => 'الشبه طبي',
                'phase_key' => 'paramedical',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الرابعة',
                'phase' => 'الشبه طبي',
                'phase_key' => 'paramedical',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الخامسة',
                'phase' => 'الشبه طبي',
                'phase_key' => 'paramedical',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'مفصول',
                'phase' => 'اخر',
                'phase_key' => 'other',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'امي',
                'phase' => 'اخر',
                'phase_key' => 'other',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الأولى',
                'phase' => 'التكوين المهني',
                'phase_key' => 'vocational_training',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الثانية',
                'phase' => 'التكوين المهني',
                'phase_key' => 'vocational_training',
                'subject_ids' => null,
            ],
            [
                'id' => Str::uuid(),
                'level' => 'السنة الثالثة',
                'phase' => 'التكوين المهني',
                'phase_key' => 'vocational_training',
                'subject_ids' => null,
            ],
        ];

        AcademicLevel::insert($rows);
    }
}
